### ISSUE TITLE
XConnect automationengine fails to start when connected to VPN.

### ISSUE THREAD

**Issue by phaniav** [Sitecore/docker-images#135]
Team,
while trying to run a docker container on Friday, I ran into the below issue. I didn't run into this issue prior and I was using the same images from my previous build which ran successfully. 

Upon further analysis of when this issue occurs, I noticed that I was on force tunnel VPN to my company when I tried to run the docker on my laptop.

Is this a known issue? I haven't found anything related to this error that is in either closed or open issues. So, bringing it to your notice. I haven't investigated how to resolve this yet. But if you are already aware of the problem, want to know if there is any workaround to this issue?

I have listed my machine configuration and VPN client details below the error stacktrace.  

```
xconnect-automationengine_1  | 2019-11-15 23:18:57 ERR Error initializing XConnect client.
xconnect-automationengine_1  | System.AggregateException: One or more errors occurred. ---> Sitecore.XConnect.XdbCollectionUnavailableException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'xconnect'
xconnect-automationengine_1  |    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
xconnect-automationengine_1  |    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
xconnect-automationengine_1  |    --- End of inner exception stack trace ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.<ExecuteAsync>d__41.MoveNext()
xconnect-automationengine_1  | --- End of stack trace from previous location where exception was thrown ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.<ExecuteGetAsync>d__36.MoveNext()
xconnect-automationengine_1  | --- End of stack trace from previous location where exception was thrown ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.WebApi.ConfigurationWebApiClient.<Refresh>d__6.MoveNext()
xconnect-automationengine_1  |    --- End of inner exception stack trace ---
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.WebApi.ConfigurationWebApiClient.<Refresh>d__6.MoveNext()
xconnect-automationengine_1  | --- End of stack trace from previous location where exception was thrown ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.XConnectClientConfiguration.<InitializeAsync>d__32.MoveNext()
xconnect-automationengine_1  |    --- End of inner exception stack trace ---
xconnect-automationengine_1  |    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
xconnect-automationengine_1  |    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.Configuration.XConnect.Extensions.ServiceCollectionExtensions.<>c__DisplayClass1_0.<UseXConnectClientConfiguration>b__0(IServiceProvider provider)
xconnect-automationengine_1  | ---> (Inner Exception #0) Sitecore.XConnect.XdbCollectionUnavailableException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'xconnect'
xconnect-automationengine_1  |    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
xconnect-automationengine_1  |    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
xconnect-automationengine_1  |    --- End of inner exception stack trace ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.<ExecuteAsync>d__41.MoveNext()
xconnect-automationengine_1  | --- End of stack trace from previous location where exception was thrown ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.Xdb.Common.Web.CommonWebApiClient`1.<ExecuteGetAsync>d__36.MoveNext()
xconnect-automationengine_1  | --- End of stack trace from previous location where exception was thrown ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.WebApi.ConfigurationWebApiClient.<Refresh>d__6.MoveNext()
xconnect-automationengine_1  |    --- End of inner exception stack trace ---
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.WebApi.ConfigurationWebApiClient.<Refresh>d__6.MoveNext()
xconnect-automationengine_1  | --- End of stack trace from previous location where exception was thrown ---
xconnect-automationengine_1  |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
xconnect-automationengine_1  |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.XConnectClientConfiguration.<InitializeAsync>d__32.MoveNext()<---
xconnect-automationengine_1  | ERROR
xconnect-automationengine_1  | System.InvalidOperationException: This configuration has not been initialized. Please call the initialize method before using it.
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.XConnectClientConfiguration.CheckInitialized()
xconnect-automationengine_1  |    at Sitecore.XConnect.Client.XConnectClientC
xconnect-automationengine_1  |
xconnect-automationengine_1  | onfiguration.get_CurrentModel()
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
xconnect-automationengine_1  |    at Sitecore.XConnect.Configuration.Extensions.<>c__DisplayClass24_0.<UseServiceDecorator>b__1(IServiceProvider provider)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
xconnect-automationengine_1  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
xconnect-automationengine_1  |    at Sitecore.Xdb.MarketingAutomation.Engine.App.ServiceConfiguration.get_Engine()
xconnect-automationengine_1  |    at Sitecore.Xdb.MarketingAutomation.Engine.App.Program.RunAsConsoleApp(Boolean interactive)
9xx_xconnect-automationengine_1 exited with code 0
```
My machine configuration
![image](https://user-images.githubusercontent.com/3968213/69024323-dc54c780-0987-11ea-913b-70cc2dd25ae0.png)

![image](https://user-images.githubusercontent.com/3968213/69024362-0c9c6600-0988-11ea-863d-11b1e0ac874a.png)

VPN client:
![image](https://user-images.githubusercontent.com/3968213/69024413-43727c00-0988-11ea-8f02-4a3a39d56729.png)

Thanks
Phani Abburi

**Comment by pbering** [comment]
Hi, I'm sorry but this is not an issue with images from this repo. The only trick I know of that may help you is to run `Get-NetIPInterface -AddressFamily IPv4 | Sort-Object -Property InterfaceMetric -Descending` and make sure that the adapter that gives you internet has the lowest metric value. You can set it with `Set-NetIPInterface -InterfaceAlias 'Wi-Fi' -InterfaceMetric 3`. Otherwise you should also make sure that you configure your VPN to use your local gateway and not the remote gateway.

If nothing of above works, you should create a issue over at: https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissue+VPN
