### ISSUE TITLE
Missing JssImport user on JSS image variant

### ISSUE THREAD

**Issue by reyrahadian** [Sitecore/docker-images#41]
I'm using the JSS variant image from this repo with the docker image details below:

- sitecore-xm1-jss-11.0.1-sqldev:9.1.1-windowsservercore-ltsc2019       
- sitecore-xm1-jss-11.0.1-cm:9.1.1-windowsservercore-ltsc2019

On startup I can see the home page just fine, however as soon as I start to try and to deploy the JSS app to Sitecore I started to get the following exception.

```
Exception thrown while importing JSS app
Exception: Sitecore.Exceptions.AccessDeniedException
   at Sitecore.JavaScriptServices.AppServices.ImportService.ImportJob.StartImportInternal()


Import is complete.

IMPORT ERROR(S) OCCURRED!
Exception thrown while importing JSS app
Exception: Sitecore.Exceptions.AccessDeniedException
Message: AddFromTemplate - Add access required (destination: {825B30B4-B40B-422E-9920-23A1B6BDA89C}, template: {0437FEE2-44C9-46A6-ABE9-28858D9FEE8C})
Source: Sitecore.Kernel
   at Sitecore.Diagnostics.Assert.HasAccess(Boolean accessAllowed, String message)
   at Sitecore.Data.Managers.ItemProvider.AddFromTemplate(String itemName, ID templateId, Item destination, ID newId)
   at Sitecore.Data.Managers.DefaultItemManager.AddFromTemplate(String itemName, ID templateId, Item destination, ID newItemId)
   at Sitecore.Data.Managers.ItemManager.AddFromTemplate(String itemName, ID templateId, Item destination, ID newItemId)
   at Sitecore.Data.Items.Item.Add(String name, TemplateID templateID, ID newItemID)
   at Sitecore.JavaScriptServices.AppServices.Data.ItemPathCreator.CreateItemPath(Database db, String path, TemplateItem folderTemplate, TemplateItem itemTemplate, String idNamespace, IdManager idManager, AppConfiguration app, ID targetItemId)
   at Sitecore.JavaScriptServices.AppServices.Data.ItemPathCreator.GetOrCreatePath(Database database, String path, TemplateItem folderTemplate, TemplateItem itemTemplate, String idNamespace, IdManager idManager, AppConfiguration app, Boolean& isNew)
   at Sitecore.JavaScriptServices.AppServices.Data.ItemPathCreator.GetOrCreatePath(Database database, String path, TemplateItem folderTemplate, TemplateItem itemTemplate, String idNamespace, IdManager idManager, AppConfiguration app)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.CreateTemplatesContainer.DoProcess(ImportPipelineArgs args, Database database, ItemPathCreator itemPathCreator)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ImportPipeline.Import(ImportPipelineArgs args)
   at Sitecore.JavaScriptServices.AppServices.ImportService.ImportJob.StartImportInternal()
```
After fiddling around, I've noticed that the JSS Import user is missing and reinstalling the JSS zip package and rerunning the import seems to have to confirm the issue. This might be due to the fact that during docker build process, the JSS Import user from the package is not saved somewhere (either serialized to the file system or in a database)

I've looked at other Docker image repo from the community and it seems this repo solve the problem by approaching it differently.

- Use Docker compose to start the containers then install the JSS package 
  - https://github.com/avivasolutionsnl/sitecore-docker/blob/85d5381ea25ebfd230e47a011b6a6f97dba802ee/build/Build.cs#L112
- Then save the database state using Docker commit and push that to the Docker registry
  - https://github.com/avivasolutionsnl/sitecore-docker/blob/master/build/Build.Xp.cs#L264

**Comment by pbering** [comment]
Hi, thank you for reporting. This is a known issue with the WDP packages and I think that @bplasmeijer has a open issue at Sitecore support regarding this. @bplasmeijer can you elaborate?

**Comment by gbxe** [comment]
I have just tried to build images from the most recent Docker files from the GitHub repo (this repo). I did have time and a need to test JSS import, nevertheless, the Role and the Users seem to be created correctly.

![image](https://user-images.githubusercontent.com/21163169/68873013-3bec7200-06ff-11ea-8afd-018c3fd033db.png)
